debug: false
#服务器配置
server: 
  port: 8089
  session:
    persistent: true
#实体类扫描的包名
mybatis:
  type-aliases-package: com.jrsoft.*.entity
#数据源配置
spring:
  application:
    name: Kaidi-ots
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kaidi_ots?characterEncoding=utf-8
    username: root
    password: cope9020
    dbcp:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
#模板配置
  thymeleaf:
    cache: false
    check-template: false
    content-type: text/html
    encoding: UTF-8
#邮箱配置
  mail:
    protocol: smtp
    host: smtp.263.net
    port: 25
    properties:
      mail.smtp.auth: true
    username: order@zjkaideli.com
    password: kd366216
    default-encoding: UTF-8
#分页配置
pageSize: 25